source ~/.config/zsh/init.zsh
source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug 'dracula/zsh', as:theme
zplug 'akash329d/zsh-alias-finder'
#zplug 'Valiev/almostontop'
zplug 'Junker/zsh-archlinux'
zplug 'ael-code/zsh-colored-man-pages'
zplug 'bossjones/boss-git-zsh-plugin'
zplug 'webyneter/docker-aliases'
zplug 'TwoPizza9621536/zsh-exa'
zplug 'zdharma-continuum/fast-syntax-highlighting'
zplug 'wfxr/forgit'
zplug 'amstrad/oh-my-matrix'
zplug 'zsh-users/zsh-completions'
if ! zplug check; then
    zplug install
fi

zplug load 
